--@Autor: FLores García Karina
--@Autor: Herrera Gandarela Gabriel Alejandro
--@Fecha Creacion: 07/02/2021
--@Descripcion: Insercion a tabla modelo
connect admin_objects/aobjects

insert into modelo (modelo_id, nombre_modelo, marca_id) values (1, 'Justy', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (2, 'Compass', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (3, 'Sierra 1500', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (4, 'Metro', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (5, 'Mariner', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (6, 'Camaro', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (7, 'Protege', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (8, 'Taurus', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (9, 'Mustang', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (10, 'Corvette', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (11, 'Supra', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (12, 'Silverado 2500', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (13, 'Econoline E250', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (14, 'Escort', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (15, 'Justy', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (16, 'xB', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (17, 'H1', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (18, 'Quest', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (19, 'Mirage', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (20, 'Prizm', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (21, 'Sonata', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (22, 'Tercel', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (23, 'Countach', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (24, 'Viper', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (25, 'Mirage', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (26, 'MKZ', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (27, 'Regal', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (28, 'Quattroporte', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (29, 'Corvette', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (30, 'Jetta', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (31, 'Envoy XUV', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (32, 'HHR', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (33, 'Sprinter 2500', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (34, 'Sienna', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (35, 'RX-7', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (36, 'H1', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (37, '4Runner', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (38, '911', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (39, 'Protege', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (40, 'Verona', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (41, 'MPV', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (42, 'RL', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (43, '850', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (44, '911', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (45, 'Pajero', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (46, 'Exige', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (47, 'E-Series', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (48, 'HHR', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (49, '900', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (50, 'Sonoma', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (51, 'Galant', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (52, 'Suburban 1500', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (53, 'Corvette', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (54, 'X3', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (55, '9-3', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (56, 'Trooper', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (57, 'New Beetle', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (58, 'Crown Victoria', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (59, 'H1', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (60, 'Town Car', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (61, 'Corvette', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (62, 'M3', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (63, 'Sonoma Club', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (64, 'Grand Caravan', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (65, 'Excursion', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (66, 'LHS', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (67, 'Sonoma', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (68, '300ZX', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (69, 'TSX', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (70, 'Ranger', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (71, 'Cultus', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (72, 'DBS', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (73, 'LeMans', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (74, 'Vega', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (75, '300SL', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (76, 'NSX', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (77, 'Cutlass', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (78, 'Accent', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (79, 'Scoupe', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (80, 'Vandura G1500', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (81, 'SLR McLaren', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (82, 'Boxster', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (83, 'XJ Series', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (84, 'Ranger', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (85, 'A6', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (86, 'Sorento', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (87, 'Tempo', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (88, '6000', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (89, 'Exige', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (90, 'Ranger', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (91, 'Clubman', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (92, 'Freestar', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (93, 'Range Rover', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (94, 'Durango', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (95, 'Rodeo Sport', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (96, 'Explorer Sport Trac', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (97, 'Catera', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (98, 'Prius', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (99, 'GTI', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (100, 'Metro', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (101, 'Cube', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (102, 'Mighty Max', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (103, 'Mustang', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (104, '911', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (105, 'RL', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (106, 'Sienna', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (107, 'Pilot', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (108, 'Accord', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (109, 'F-Series', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (110, 'Corvette', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (111, 'Laser', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (112, 'H1', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (113, 'Silhouette', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (114, '6000', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (115, 'Xterra', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (116, 'SRX', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (117, 'Park Avenue', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (118, '4Runner', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (119, 'CLS-Class', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (120, 'Legacy', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (121, 'Sierra 2500HD', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (122, 'Trans Sport', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (123, 'Firefly', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (124, 'Camaro', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (125, 'Quattroporte', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (126, 'Cayenne', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (127, 'Mustang', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (128, 'Avalon', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (129, 'Savana 2500', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (130, 'Civic', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (131, 'Sedona', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (132, 'Q', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (133, '911', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (134, 'C-Class', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (135, 'Corvette', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (136, 'Corvair 500', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (137, 'Tempo', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (138, 'HHR', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (139, 'Legend', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (140, 'Cougar', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (141, 'XG350', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (142, 'Tercel', 6);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (143, 'E-Series', 7);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (144, 'Flex', 8);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (145, 'Ion', 1);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (146, 'X-Type', 2);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (147, 'Crossfire', 3);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (148, 'Yukon', 4);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (149, 'F150', 5);
insert into modelo (modelo_id, nombre_modelo, marca_id) values (150, 'Corolla', 6);
